name: Continuous Delivery

on:
  push:
    tags:
      - 'v*'
    branches-ignore:
      - '**'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  release:
    name: Release
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
      deployments: write
      id-token: write

  # Needs Tokens checks:
  # Ref: https://github.com/infinyon/fluvio-docs/actions/runs/10117625792/job/27982994143#step:6:1
  #
  # deploy:
  #   name: Deploy
  #   needs: release
  #   uses: ./.github/workflows/deploy.yml
  #   permissions:
  #     contents: write
  #     deployments: write
  #     id-token: write
  #   secrets:
  #     CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  #     CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #   with:
  #     project_name: fluvio-docs-nightly

  deploy_tmp:
    name: Deploy Temporal Site
    needs: release
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: write
      deployments: write
      id-token: write
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.TMP_CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.TMP_CLOUDFLARE_API_TOKEN }}
    with:
      project_name: fluvio-docs
